-- ======================================================
-- SiirtEsnafCep - Supabase Veritabanı Kurulum Kodu
-- ======================================================

CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    icon TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'catalog',
    tags TEXT,
    districts TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.merchants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    business_name TEXT,
    category_slug TEXT REFERENCES public.categories(slug) ON DELETE SET NULL,
    district TEXT NOT NULL,
    address TEXT,
    phone TEXT NOT NULL,
    avatar TEXT,
    avatar_bg TEXT,
    rating NUMERIC(3,2) DEFAULT 0.0,
    review_count INT DEFAULT 0,
    is_verified BOOLEAN DEFAULT false,
    is_247 BOOLEAN DEFAULT false,
    delivery_time TEXT,
    description TEXT,
    tags TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.ads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT REFERENCES public.merchants(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    price NUMERIC(12,2) NOT NULL,
    image TEXT,
    category_slug TEXT REFERENCES public.categories(slug) ON DELETE SET NULL,
    district TEXT NOT NULL,
    location TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT REFERENCES public.merchants(id) ON DELETE CASCADE,
    user_name TEXT NOT NULL,
    user_email TEXT,
    rating INT CHECK (rating >= 1 AND rating <= 5),
    comment TEXT NOT NULL,
    is_approved BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.merchants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Herkes kategorileri görebilir" ON public.categories;
DROP POLICY IF EXISTS "Herkes esnafları görebilir" ON public.merchants;
DROP POLICY IF EXISTS "Herkes ilanları görebilir" ON public.ads;
DROP POLICY IF EXISTS "Herkes yorumları görebilir" ON public.reviews;

CREATE POLICY "Herkes kategorileri görebilir" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Herkes esnafları görebilir" ON public.merchants FOR SELECT USING (true);
CREATE POLICY "Herkes ilanları görebilir" ON public.ads FOR SELECT USING (true);
CREATE POLICY "Herkes yorumları görebilir" ON public.reviews FOR SELECT USING (true);

INSERT INTO public.categories (slug, title, icon, type, tags, districts) VALUES
('cekici', 'Çekici & Oto Kurtarma', '🚗', 'urgent', 'cekici oto kurtarma yol yardim', 'merkez kurtalan baykan'),
('taksi', 'Taksi & Özel Ulaşım', '🚕', 'urgent', 'taksi duragi ulasim binek', 'merkez kurtalan'),
('cilingir', 'Çilingir & Anahtarcı', '🔑', 'urgent', 'cilingir anahtar kilit kapi', 'merkez eruh sirvan'),
('elektrik', 'Elektrik Tesisat Ustası', '🔌', 'urgent', 'elektrik elektrikci aydinlatma ariza', 'merkez kurtalan pervari'),
('tesisat', 'Sıhhi Tesisat & Su Tamircisi', '💧', 'urgent', 'tesisat su tesisatci', 'merkez baykan'),
('kombi', 'Kombi & Klima Tamir Servisi', '🔥', 'urgent', 'kombi klima bakim tamir', 'merkez'),
('mobilya', 'Mobilya & Koltuk Takımları', '🪑', 'catalog', 'mobilya koltuk masa yatak dolap', 'merkez kurtalan'),
('telefon', 'Telefon Tamir & Aksesuar', '📱', 'catalog', 'telefon tamir kilif aksesuar iphone', 'merkez'),
('emlak', 'Emlak & Gayrimenkul', '🏠', 'catalog', 'emlak kiralik satilik daire arsa', 'merkez eruh baykan'),
('galeri', 'Oto Galeri & 2. El Araç', '🚘', 'catalog', 'galeri oto araba vasita satilik', 'merkez kurtalan'),
('marangoz', 'Marangoz & Özel Mobilya', '🪚', 'catalog', 'marangoz ahsap mobilya imalat', 'merkez baykan'),
('beyaz-esya', 'Beyaz Eşya & Spot', '❄️', 'catalog', 'beyaz esya spot buzdolabi camasir', 'merkez kurtalan'),
('hali-perde', 'Halı & Perde Dünyası', '🪟', 'catalog', 'hali perde stor zebra', 'merkez'),
('ceyiz', 'Çeyiz & Ev Tekstili', '🎁', 'catalog', 'ceyiz ev tekstili yatak ortusu', 'merkez'),
('gelinlik', 'Gelinlik & Abiye Mağazaları', '👗', 'catalog', 'gelinlik abiye dugun nisan', 'merkez kurtalan'),
('yoresel', 'Yöresel Ürünler & Siirt Battaniyesi', '🍯', 'catalog', 'yoresel fistik battaniye bal', 'merkez eruh pervari'),
('nalbur', 'Nalbur & Yapı Market', '🧱', 'catalog', 'nalbur yapi market boya cimento', 'merkez kurtalan baykan'),
('boya', 'Boya, Badana & Alçı Ustası', '🖌️', 'catalog', 'boya badana alci boyaci', 'merkez'),
('cicekci', 'Çiçekçi & Hediye Mağazaları', '💐', 'catalog', 'cicekci hediye aranjman gul', 'merkez'),
('dugun', 'Düğün & Nişan Organizasyonu', '🎉', 'catalog', 'dugun nisan kina organizasyon salon', 'merkez'),
('bilgisayar', 'Bilgisayar & Konsol Servisi', '💻', 'catalog', 'bilgisayar pc laptop konsol ps5', 'merkez'),
('nakliyat', 'Evden Eve Nakliyat', '🚚', 'catalog', 'nakliyat evden eve tasimacilik', 'merkez kurtalan'),
('temizlik', 'Ev ve Ofis Temizlik', '✨', 'catalog', 'temizlik sirketi ofis ev', 'merkez'),
('terzi', 'Terzi & Kıyafet Tadilatı', '✂️', 'catalog', 'terzi tadilat dikim kiyafet', 'merkez'),
('ayakkabi', 'Ayakkabı & Çanta Mağazaları', '👞', 'catalog', 'ayakkabi canta bot spor', 'merkez'),
('kuyumcu', 'Kuyumcu & Gümüşçü', '💍', 'catalog', 'kuyumcu altin bilezik gumus', 'merkez'),
('saat', 'Saat & Optik Mağazaları', '⌚', 'catalog', 'saat optik gozluk', 'merkez'),
('kirtasiye', 'Kırtasiye & Kitabevleri', '📚', 'catalog', 'kirtasiye defter kitap kalem okul', 'merkez'),
('matbaa', 'Matbaa & Dijital Baskı', '🖨️', 'catalog', 'matbaa baski davetiye reklam brosur', 'merkez'),
('reklam', 'Reklam & Tabela Üretimi', '🪧', 'catalog', 'reklam tabela isikli kutu harf', 'merkez'),
('oto-yikama', 'Oto Yıkama & Kuaför', '🧽', 'catalog', 'oto yikama kuafor detayli temizlik', 'merkez kurtalan'),
('oto-lastik', 'Oto Lastik Satış & Tamir', '🛞', 'catalog', 'oto lastik jant rot balans', 'merkez baykan'),
('alcipan', 'Alçıpan & Asma Tavan', '🏗️', 'catalog', 'alcipan asma tavan dekorasyon', 'merkez'),
('camci', 'Camcı & Pimapen İmalatı', '🪟', 'catalog', 'camci pimapen pvc pencere', 'merkez'),
('gunes-enerjisi', 'Güneş Enerjisi Sistemleri', '☀️', 'catalog', 'gunes enerjisi isi su', 'merkez eruh'),
('demir-dograma', 'Demir Doğrama & Kaynak', '⛓️', 'catalog', 'demir dograma kaynak ferforje', 'merkez'),
('hali-yikama', 'Halı Yıkama Fabrikaları', '🧼', 'catalog', 'hali yikama kilim yolluk', 'merkez kurtalan'),
('kuru-temizleme', 'Kuru Temizleme & Ütü Evi', '👔', 'catalog', 'kuru temizleme utu camasir', 'merkez'),
('petshop', 'Petshop & Evcil Hayvan', '🐾', 'catalog', 'petshop mama yem kedi kopek', 'merkez'),
('zuccaciye', 'Züccaciye & Ev Gereçleri', '🍽️', 'catalog', 'zuccaciye mutfak bardak tencere ev', 'merkez baykan')
ON CONFLICT (slug) DO NOTHING;
